### ISSUE TITLE
Tesseract Changes

### ISSUE THREAD

**Issue by jrgnicho** [swri-robotics/collaborative-robotic-sanding#15]
The latest changes in the tesseract repo aren't compatible with the free space motion planner node

**Comment by gavanderhoorn** [comment]
Suggestion: instead of tracking `master` or similar branches in `crs.rosinstall`, specify known working commits in the `version` key.

Updating to include upstream changes would then be a deliberate action and you'd avoid upstream breaking the application.

**Comment by marrts** [comment]
@gavanderhoorn thank you for this suggestion, I have applied it along with fixing the breaking changes that occurred from the latest tesseract update in my pull request.
