### ISSUE TITLE
Add gazebo_ros to rosdep

### ISSUE THREAD

**Issue by mpowelson** [swri-robotics/collaborative-robotic-sanding#27]
Gazebo_ros does not get installed by rosdep. It looks like there isn't a rosdep key for it? We have gazebo in crs_support, but that doesn't seem to do it. Am I missing something? I can't run environment_launch.launch.py until I have manually installed gazebo_ros

**Comment by gavanderhoorn** [comment]
For plain Gazebo 9, `gazebo9` should be the key. See [here](https://github.com/ros/rosdistro/blob/f9999563f4ac8ebe54245ac7301bba0a3af00a00/rosdep/base.yaml#L909-L922).

If you use any of the plugins from `gazebo_ros`, the dependency would be `gazebo_ros`.

`gazebo_ros_pkgs` is a metapackage and should not be `depend`ed on.

> It looks like there isn't a rosdep key for it?

ROS pkgs don't have a `rosdep` key. Those are only for non-ROS dependencies (ie: system dependencies).

**Comment by mpowelson** [comment]
Ok. I didn't realize that ros packages didn't need an explicit key. I guess if I had been observant I would have noticed that none of them started with ros-...

 Yeah, I guess we just need to add gazebo_ros in addition to gazebo. Thanks.

**Comment by gavanderhoorn** [comment]
> Ok. I didn't realize that ros packages didn't need an explicit key. I guess if I had been observant I would have noticed that none of them started with ros-...

well, they do need to be listed as dependencies, but they don't have a *key* in the `rosdep` DB. `rosdep` is smart enough to figure out those are actually ROS pkgs, not system dependencies.

> Yeah, I guess we just need to add gazebo_ros in addition to gazebo. Thanks.

`gazebo_ros` already depends on `gazebo_dev` ([here](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/63bec81820a3774054172da19385ff267b117df4/gazebo_ros/package.xml#L26)), which in the end depends on Gazebo 9 itself (via [here](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/63bec81820a3774054172da19385ff267b117df4/gazebo_dev/package.xml#L23)) (at least in Dashing/Eloquent).

**Comment by mpowelson** [comment]
Addressed in #33
