### ISSUE TITLE
Iterative Spline Parameterization rosdep

### ISSUE THREAD

**Issue by mpowelson** [swri-robotics/collaborative-robotic-sanding#45]
@marrts This was removed rather intentionally in #38. Why? It is still used in the cmake by ${PROJECT_NAME}_path_processing_utils. Should it be removed there as well?

**Comment by marrts** [comment]
I removed it because of it caused issues with CI passing, I should be in both places.

**Comment by mpowelson** [comment]
You'll need to add it to the travis ROSDEP_SKIP_KEYS since it is pure cmake. I had forgotten that. See [HERE](https://github.com/swri-robotics/collaborative-robotic-sanding/blob/035b8b3fee8486bfb68dc1fdc44fe477a1ead53f/.travis.yml#L25)

**Comment by mpowelson** [comment]
Not having it in the package.xml could cause problems (and actually did on my local machine) if ISP is not done building by the time motion planning starts.

**Comment by marrts** [comment]
Okay that is good to know, feel free to go ahead and modify the travis file unless you want me to do that.

**Comment by mpowelson** [comment]
Also, this is a known issue on Industrial CI. I believe it was a regression. Somewhere one of the developers had a fork with a working fix (I'd have to dig around. Levi I think had an issue open). The point is, this should not be an issue forever. This is a temporary work around.

**Comment by marrts** [comment]
So does this mean that CI could potentially fail since it isn't respecting all of the dependencies in a similar way to what you experienced on your machine when I excluded ISP from the package.xml?

**Comment by mpowelson** [comment]
colcon will still respect the dependency in the build order. rosdep just won't fail when it can't find it.
