### ISSUE TITLE
Duplicate Code: crs_motion_planning::tesseractRosutilsToMsg

### ISSUE THREAD

**Issue by mpowelson** [swri-robotics/collaborative-robotic-sanding#49]
What is the purpose of this conversion? It is nearly identical to the one in tesseract_ros2 except one uses rclcpp::Duration and one uses chrono. Is this a bug fix that should be pushed back or did the other conversion just not exist at the time?

**Comment by mpowelson** [comment]
@marrts

**Comment by marrts** [comment]
There is no reason for this redundant function, it was an artifact from before rosutils was fully migrated.
