### ISSUE TITLE
Update Docker with new dependencies

### ISSUE THREAD

**Issue by mpowelson** [swri-robotics/collaborative-robotic-sanding#70]
@jrgnicho What needs to be added? Is it just librealsense SDK? What version do you want?

Add

- [ ] librealsense SDK - version: ??

**Comment by jrgnicho** [comment]
I believe the following is needed
[Framos Depth Camera](https://www.framos.com/en/industrial-depth-cameras#downloads).  Download and Extract the [tar file](https://www.framos.com/framos3d/D400e/Software/FRAMOS_D400e_Software_Package_v1-8-0_Linux64_x64.tar.gz) and then install the FRAMOS-librealsense2-2.29.8-Linux64_x64.deb debian

@marrts could you think of anything else that I'm missing?

**Comment by mpowelson** [comment]
Just taking a quick look at the repo, it doesn't look like there are really any unit tests anyway. Can you not just take the realsense repo and put that in a hardware rosinstall? I would think that you wouldn't have to install the framos driver to run in simulation.

**Comment by jrgnicho** [comment]
That is a good suggestion actually, I'll create a supplemental hardware dependencies ros install file with the required libraries for the hardware alone

**Comment by mpowelson** [comment]
So do you still want me to try to add that to the docker or should I close this?

**Comment by jrgnicho** [comment]
Lets keep it open until the ci passes once I make the change but changes to the docker won't be necessary for now.  Thanks
